# Generated by Django 5.0.3 on 2024-03-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tashxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sick', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('narx', models.PositiveIntegerField(default=0)),
                ('tuladi', models.PositiveIntegerField(default=0)),
                ('qoldi', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
