# Generated by Django 5.0.3 on 2024-03-17 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_alter_tashxis_bemor_alter_tashxis_user'),
        ('User', '0002_remove_bemor_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tashxis',
            name='bemor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tashxis_user', to='User.bemor'),
        ),
        migrations.AlterField(
            model_name='tashxis',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tashxis_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
