# Generated by Django 5.0.3 on 2024-03-17 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_remove_tashxis_user'),
        ('User', '0002_remove_bemor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tashxis',
            name='bemor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tashxis_bemor', to='User.bemor'),
        ),
    ]
